In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

This is a coding along *5. The Basics of NumPy Arrays*.

## Getting data

In [2]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility
x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array

## NumPy Array Attributes

In [3]:
x3.ndim, x3.shape, x3.size, x3.dtype

(3, (3, 4, 5), 60, dtype('int64'))

## Array Slicing: Accessing Subarrays

### One-Dimensional Subarrays

Let's have a look at some non-trivial slicing.

In [4]:
x1

array([9, 4, 0, 3, 8, 6])

In [8]:
x1[1:5]

array([4, 0, 3, 8])

In [6]:
# every second element starting at index 1
x1[1::2]

array([4, 3, 6])

In [7]:
# reversing the array (as we know)
x1[::-1]

array([6, 8, 3, 0, 4, 9])

In [8]:
# every second element in reversed order (NEW)
x1[::-2]

array([6, 3, 4])

### Multidimensional Subarrays

In [9]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [10]:
x2[:2, :]

array([[3, 1, 3, 7],
       [4, 0, 2, 3]])

In [11]:
x2[2:, :]

array([[0, 0, 6, 9]])

In [12]:
x2[:2, :3]

array([[3, 1, 3],
       [4, 0, 2]])

In [13]:
x2[:2, 3:]

array([[7],
       [3]])

In [14]:
x2[2:, :3]

array([[0, 0, 6]])

In [15]:
x2[2:, 3:]

array([[9]])

Let's also have a look at negative indicies.

In [16]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [17]:
x2[:, :-1]

array([[3, 1, 3],
       [4, 0, 2],
       [0, 0, 6]])

In [18]:
x2[:, -1:]

array([[7],
       [3],
       [9]])

In [19]:
x2[:, :-2]

array([[3, 1],
       [4, 0],
       [0, 0]])

In [20]:
x2[:, -2:]

array([[3, 7],
       [2, 3],
       [6, 9]])

In [21]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [22]:
# reversed order for rows
x2[:, ::-1]

array([[7, 3, 1, 3],
       [3, 2, 0, 4],
       [9, 6, 0, 0]])

In [23]:
# reversed order for columns
x2[::-1, :]

array([[0, 0, 6, 9],
       [4, 0, 2, 3],
       [3, 1, 3, 7]])

We may do reversed order both for rows and columns, but we're not doing this.

### Subarrays as No-Copy Views

> Unlike Python list slices, NumPy array slices are returned as *views* rather than *copies* of the array data.
> Some users may find this surprising, but it can be advantageous: for example, when working with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

In [24]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [25]:
x2_sub = x2[:2, :2]

In [26]:
x2_sub

array([[3, 1],
       [4, 0]])

In [27]:
x2_sub[0, 0] = 99

In [28]:
x2_sub

array([[99,  1],
       [ 4,  0]])

In [29]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

So as we may see `x2` is also changed.

### Creating Copies of Arrays

In [30]:
x2_sub_copy = x2[:2, :2].copy()

In [31]:
x2_sub_copy

array([[99,  1],
       [ 4,  0]])

In [32]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [33]:
x2_sub_copy[0, 0] = 42

In [34]:
x2_sub_copy

array([[42,  1],
       [ 4,  0]])

In [35]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

No changes in the original array.