In [1]:
import numpy as np
import pandas as pd

This is chapter 6 Computation on NumPy Arrays: Universal Functions. It seems this is important not only for NumPy, but for Pandas as well.

## The Slowness of Loops

In [2]:
rng = np.random.default_rng(seed=1701)

In [3]:
# for [a, b, c] compute [1/a, 1/b, 1/c]
def compute_reciprocals(values): 
    output = np.empty(len(values)) 
    for i in range(len(values)):
        output[i] = 1.0 / values[i] 
    return output

In [4]:
big_array = rng.integers(1, 100, size=10_000_000)

In [5]:
%timeit compute_reciprocals(big_array)

5.93 s ± 48.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Introducing Ufuncs

Let's compare this with NumPy ufuncs.

In [6]:
print(f"{big_array.size:_}")

10_000_000


In [7]:
%timeit (1.0 / big_array)

7.23 ms ± 86 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Exploring NumPy’s Ufuncs

- Array Arithmetic. First of all, all usual Python operators are overloaded for use with NumPy arrays.
- Absolute values. We also have analogues for some functions in Python, for example, `np.abs` to get an absolute value.

It's interesting that we may exponentiate an array or use it as an exponent itself.

In [16]:
x = np.array([1, 2, 3])

In [17]:
x ** 2

array([1, 4, 9])

In [23]:
np.power(x, 2)

array([1, 4, 9])

In [22]:
np.power(2, x)

array([2, 4, 8])

Not clear if we can use `^` instead of this as in the book. It does not seem to work.

Here's some advanced Ufunc features:
- First of all, we may specify the result array. This may reduce the number of copies.
- There's a famous `reduce()` function:
> A reduce repeatedly applies a given operation to the elements of an array until only a single result remains. If we’d like to store all the intermediate results of the computation, we can instead use `accumulate()`.

In [24]:
x = np.arange(1, 6)

In [25]:
x

array([1, 2, 3, 4, 5])

In [26]:
np.add.reduce(x)

np.int64(15)