In [6]:
import numpy as np
import pandas as pd

# Operating on Data in Pandas

### Ufuncs: Index Preservation

In [7]:
rng = np.random.default_rng(42)
ser = pd.Series(rng.integers(0, 10, 4))

In [8]:
ser

0    0
1    7
2    6
3    4
dtype: int64

> If we apply a NumPy ufunc on either of these objects, the result will be another Pandas object with the indices preserved

In [9]:
np.exp(ser)

0       1.000000
1    1096.633158
2     403.428793
3      54.598150
dtype: float64

In [10]:
# ser.exp()

In [11]:
np.sum(ser)

np.int64(17)

In [12]:
ser.sum()

np.int64(17)

### Ufuncs: Index Alignment

> For binary operations on two Series or DataFrame objects, Pandas will align indices in the process of performing the operation.

In [13]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

In [14]:
population = pd.Series({'California': 39538223, 'Texas': 29145505,
                        'Florida': 21538187}, name='population')

In [15]:
area 

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [16]:
population

California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64

In [17]:
area / population

Alaska             NaN
California    0.010723
Florida            NaN
Texas         0.023869
dtype: float64

### Ufuncs: Operations Between DataFrames and Series

In [18]:
A = rng.integers(10, size=(3, 4))

In [19]:
A

array([[4, 8, 0, 6],
       [2, 0, 5, 9],
       [7, 7, 7, 7]])

In [20]:
A[0]

array([4, 8, 0, 6])

In [21]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-2, -8,  5,  3],
       [ 3, -1,  7,  1]])

> In Pandas, the convention similarly operates row-wise by default.

In [22]:
df = pd.DataFrame(A, columns=['Q', 'R', 'S', 'T'])

In [23]:
df

Q  R  S  T
0  4  8  0  6
1  2  0  5  9
2  7  7  7  7

In [24]:
df.iloc[0, :]

Q    4
R    8
S    0
T    6
Name: 0, dtype: int64

In [25]:
df - df.iloc[0, :]

Q  R  S  T
0  0  0  0  0
1 -2 -8  5  3
2  3 -1  7  1

In [26]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -4  0 -8 -2
1  2  0  5  9
2  0  0  0  0